### ISSUE TITLE
能不能对带拓展的APP重签名

### ISSUE THREAD

**Issue by 2856571872** [HansenCCC/HSIPAReplaceIcon#1]

**Comment by HansenCCC** [comment]
带扩展的APP，没试过唉。带什么扩展？电话拦截或者vpn哪些？

**Comment by 2856571872** [comment]
> 带扩展的APP，没试过唉。带什么扩展？电话拦截或者vpn哪些？

networkextension

**Comment by HansenCCC** [comment]
重签应该不行，这玩意有两个bundleid，不知道重签能不能都改。你可以试试

**Comment by 2856571872** [comment]
> 重签应该不行，这玩意有两个bundleid，不知道重签能不能都改。你可以试试

是的，主要就是两个bundle ID然后两个描述文件，最主要拓展还带了个App group...头大

**Comment by HansenCCC** [comment]
来都来了，也不给个star再走。过分了，宝
