### ISSUE TITLE
assets.car 有生成工具吗？，我现在的ipa替换icon那堆png无效

### ISSUE THREAD

**Issue by FozuBlessNoBug** [HansenCCC/HSIPAReplaceIcon#2]
assets.car 有生成工具吗？，我现在的ipa替换icon那堆png无效

**Comment by HansenCCC** [comment]
需要替换assets.car才行的，assets.car可以解压，但是没办法再逆向回去。我的assets.car是通过编译生成IPA之后，再show in finder拿到的。
我有个更好的方法来实现这个功能。可以直接写个脚本替换项目icon资源，替换之后再打包，这样速度会慢一点，但是是可行的。（我写的这个脚本是先打包再替换assets.car，再重签，虽然这样速度会很快，但是assets.car 生成很麻烦）。

**Comment by LiuSky** [comment]
我用了你现在的方法也是无效。
